### ISSUE TITLE
Add Lemmy spoiler support

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#127]
**Describe the bug**  

**Steps to Reproduce**  
1. Go to a post that contains a spoiler that starts and ends with :::
2. The spoiler won't be hidden

**Expected behavior**  

- It to be hidden and then be shown when clicked

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Comment by dextersgenius** [comment]
@laurencedawson 

Could I please also request that when implementing this, the spoiler content should automatically be collapsed (or provide an option for it), so that it doesn't waste space on the post?

Here's an example of how a spoiler looks like on the Lemmy fronted, by default:

![Screenshot_20230808_204138_Firefox](https://github.com/laurencedawson/sync-for-lemmy/assets/1624052/cb5b7d36-6445-4334-ada5-19fc66005657)

Link to the example.: https://lemmings.world/comment/1023146

**Comment by laurencedawson** [comment]
Added for the next beta.
