### ISSUE TITLE
Sync doesn't parse /c/ links

### ISSUE THREAD

**Issue by pwd-github** [laurencedawson/sync-for-lemmy#198]
**Describe the bug**  
Sync doesn't parse /c/ links

**Steps to Reproduce**  
1. Go to https://feddit.nl/post/1136654
2. Click on any community name 
3. Nothing happens

**Expected behavior**  
The parser should convert /c/ to !

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - Android: [e.g. 12]
 - Sync version: [e.g. v22.5.20]
 - Sync variant: [e.g. pro]

**Additional context**

**Comment by freamon** [comment]
I'm not sure about the expected behaviour. Maybe Sync shouldn't be converting anything, and just handle links with a leading '/' like web browsers do (i.e. as a link relative to where you already are). For example, on GitHub, I can link from here to somewhere else on GitHub like this: `[link](/freamon/lemmy-trending-communities-bot)` - to [demonstrate](/freamon/lemmy-trending-communities-bot)

**Comment by tigerhawkvok** [comment]
I think OP is in the right here. You're technically correct @freamon but that's not the _expected_ behavior in a mass market client app.

**Comment by laurencedawson** [comment]
Fixed for the next release. Good catch.
