### ISSUE TITLE
Redgif videos arent playing

### ISSUE THREAD

**Issue by garpunkal** [laurencedawson/sync-for-lemmy#24]
Redgifs videos arent loading but they open in browser

**Comment by laurencedawson** [comment]
Do you have an example link/

**Comment by kv1dr** [comment]
It's every redgifs video on pronlemmy.com instance. This is one of the posts: https://pornlemmy.com/post/140293
And here is redgifs url: https://www.redgifs.com/watch/remorsefulupsetdungbeetle

I would upload screenshot of the response from API, but it includes signature and hash parameters in the URL and I am not sure if I should include this here or not.

I also tried opening Redgif API response into Firefox and I got "Bad request signature.", but take that with grain of salt, because copying text from apps with Google Pixel doesn't always works the best, so it could also be an error when copying text.

**Comment by laurencedawson** [comment]
Fixed.
