### ISSUE TITLE
Paid Ad-Free APK file without AdMob bundled

### ISSUE THREAD

**Issue by KenBW2** [laurencedawson/sync-for-lemmy#250]
**Is your feature request related to a problem? Please describe.**  
I want to pay for and use Sync without having to accept the AdMob Privacy Policy

**Describe the solution you'd like**  
Ideally a Pro version of the App, but ljdawson has specified that Google Play doesn't allow that

Failing that, an APK on the Releases page of Github where I can download a version which requires verification of paid status

**Describe alternatives you've considered**  
Using the existing app. But I have to accept the Privacy Policy *before* paying for the app

**Comment by laurencedawson** [comment]
If you remove ads admob will not be initialised.

Google has previously suspended sync for having multiple versions online so I'm not going to go down the multi version road again. Sorry.

**Comment by MNLierman** [comment]
Google suspended it specifically for having multiple versions online? Can you provide a copy of this letter they sent you? There's many apps out there that have a GitHub page, XDA page, pro donate option. There's no reason why you can't even charge an in-app purchase as a one-time $6 charge to remove all ads, tracking etc. You can also include a separate APK on Play Store which incorporates those for a one-time fee, rather than doing an in-app purchase. 

To just close this and say that you're not willing to do it, well it's just that, you aren't willing to do it. If you're worried about versions of the app online,  separate Google Play paid app would easily suffice. I guarantee you will have a lot of people purchasing this, not only to support development, but also to get rid of the privacy issues of these 3rd party ad APIs. 

I ask that you reconsider.
@laurencedawson
