### ISSUE TITLE
Clicking the "Instances" button returns the error "Could not load communities."

### ISSUE THREAD

**Issue by GitWhatYouGive** [laurencedawson/sync-for-lemmy#469]

**Comment by momnom** [comment]
Some relevant posts:

https://midwest.social/post/7137297
https://lemmy.world/post/10098060
https://lemmy.world/post/9882514

I am also having the problem

[BUG] Instances button not working
---
**Description**
The Instances button (that allows us to browse other instances from the list) gives an error message instead of opening the list.

**Scenario** (steps to reproduce)**
1. Start at Subscribed or Everything feed
2. Click Instances button in Expanded Header or either of the More Actions menus

**Result(s)**
Screen flickers as the menu tries to open, but it fails with an error message:
![Screenshot_20240104-131508](https://github.com/laurencedawson/sync-for-lemmy/assets/145706131/f8e81c33-2cd3-4051-a687-6169a7a975f6)


**Device information**

    Sync version: v23.11.29-22:27    
    Sync flavor: googlePlay    
    
    View type: Smaller cards    
    Push enabled: false    
    
    Device: bluejay    
    Model: Google Pixel 6a    
    Android: 13

**Comment by FoolMeOnce** [comment]
I am also experiencing this same issue, can be reproduce with the same steps @momnom described.

**Comment by momnom** [comment]
I tried again today and it worked. I dunno if anything changed and fixed or if it was just a hiccup that several of us experienced.
![Screenshot_20240127-202021](https://github.com/laurencedawson/sync-for-lemmy/assets/145706131/3e510f53-f07d-4f5b-8ba8-5785d44c53b6)

**Comment by FoolMeOnce** [comment]
Can confirm, it also is working again for me.

**Comment by laurencedawson** [comment]
This has since been fixed.
